services:
  - type: web
    name: callbeast
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.x
    autoDeploy: true
